CREATE schema if not exists catalogue;

create table catalogue.t_item(
    id int not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    c_title varchar(50) CHECK (4 < c_title < 50),
    c_details varchar(50) check ( 4 < c_details < 50)
)