spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
    jpa:
      show-sql: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/