server:
  port: 8081

spring:
  application:
    name: catalogue-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/beststore
  flyway:
    schemas:
      - public
      - catalogue
    jpa:
      show-sql: true