server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  application:
    name: feedback-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true