beststore:
  services:
    catalogue:
      uri: lb://catalogue-service
      urifeedback: lb://feedback-service
server:
  port: 8083
spring:
  application:
    name: customer-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true